"""Create tables

Revision ID: 5c1d267f8942
Revises: 
Create Date: 2025-08-09 21:56:17.397533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1d267f8942'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds_settings',
    sa.Column('male_role_id', sa.Integer(), nullable=True),
    sa.Column('female_role_id', sa.Integer(), nullable=True),
    sa.Column('support_role_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_index(op.f('ix_guilds_settings_id'), 'guilds_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guilds_settings_id'), table_name='guilds_settings')
    op.drop_table('guilds_settings')
    # ### end Alembic commands ###
