"""Create supports_feedbacks

Revision ID: 9a15a69af279
Revises: b4572c292bd2
Create Date: 2025-08-15 15:16:03.940276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a15a69af279'
down_revision: Union[str, Sequence[str], None] = 'b4572c292bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supports_feedbacks',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('author_discord_id', sa.Integer(), nullable=False),
    sa.Column('support_discord_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supports_feedbacks_id'), 'supports_feedbacks', ['id'], unique=False)
    op.add_column('guilds_settings', sa.Column('supports_feedbacks_channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds_settings', 'supports_feedbacks_channel_id')
    op.drop_index(op.f('ix_supports_feedbacks_id'), table_name='supports_feedbacks')
    op.drop_table('supports_feedbacks')
    # ### end Alembic commands ###
