"""Added unverified_role_id

Revision ID: d5d62fc3bfd5
Revises: 5c1d267f8942
Create Date: 2025-08-10 20:59:50.895380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d62fc3bfd5'
down_revision: Union[str, Sequence[str], None] = '5c1d267f8942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds_settings', sa.Column('unverified_role_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds_settings', 'unverified_role_id')
    # ### end Alembic commands ###
